version: '3.8'

services:
  web:
    build: ./b2
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./b2:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
      - redis
    env_file:
      - .env
  celery:
    build: ./b2
    command: celery -A news worker --loglevel=info -B
    volumes:
      - ./b2:/app
    env_file:
      - .env
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres:13-alpine
    volumes:
      - ./database:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./nginx
    volumes:
      - ./b2/static:/static
    ports:
      - 127.0.0.1:80:80
